# Don't remove below line, it controls the version of golangci-linter at runtime.
# version: v1.49.0
run:
  tests: false
  skip-dirs:
    - scripts
output:
  sort-results: true
linters:
  disable:
    - gci
    - gofumpt
    - nlreturn
    - wsl
    - gochecknoglobals
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - gosec
    - nosnakecase
    - goconst
    - errorlint
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
issues:
  fix: true
