// Package config This file is generated by gob
package infra

// buildVersion don't change this, `gob build` would set this according to git commit hash
var buildVersion = "unknown"

func Version() string {
	return buildVersion
}
